project:
  type: website

website:
  title: "Max Scheijen"
  google-analytics: "G-3B00DPE6RY"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/maxscheijen
      - icon: twitter
        href: https://twitter.com/maxscheijen
  favicon: favicon.ico
comments:
  utterances:
    repo: maxscheijen/comments
format:
  html:
    theme: cosmo
    css: styles.css
