project:
  type: website

website:
  title: "Max Scheijen"
  site-url: "https://maxscheijen.com/"
  google-analytics: "G-3B00DPE6RY"
  page-footer: "Copyright 2023, Max Scheijen"
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/maxscheijen
      - icon: twitter
        href: https://twitter.com/maxscheijen
  favicon: favicon.ico
comments:
  utterances:
    repo: maxscheijen/comments
format:
  html:
    page-layout: article
    code-block-bg: false
    code-copy: false
    callout-appearance: simple
    callout-icon: false
    css: styles.css
highlight-style: ayu
resources:
  - CNAME
