baseURL: "https://maxscheijen.github.io/"
languageCode: en-us
title: Max Scheijen 
paginate: 20
theme: ["PaperMod"]

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "Max Scheijen - Blog"
  keywords: [Blog, Portfolio, Data Science, Machine Learning, AI, Python, Programming]
  author: Max Scheijen 
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false 
  ShowShareButtons: false 
  ShowPostNavLinks: true
  ShowBreadCrumbs: false 
  ShowCodeCopyButtons: true 
  ShowWordCount: false
  ShowFullTextinRSS: true
  disableSpecial1stPost: false 
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my website. I'm Max, a Data Scientist and Machine Learning Engineer from Amsterdam. On this page I share my interests, thoughts and learnings."

  socialIcons:
    - name: github
      url: "https://github.com/maxscheijen"
    - name: x
      url: "https://x.com/maxscheijen"
    - name: linkedin
      url: "https://www.linkedin.com/in/max-scheijen/"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"
  analytics:
    google:
      SiteVerificationTag: "G-HK7V1ZKCPD"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: tags 
      name: Tags 
      url: /tags/
      weight: 10
    - identifier: archive 
      name: Archive 
      url: /archive/
      weight: 20
    - identifier: search 
      name: Search 
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
