<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Max Scheijen">
<meta name="dcterms.date" content="2022-08-09">

<title>Max Scheijen - Hypothesis Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-154715114-1', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Max Scheijen</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">About</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/maxscheijen"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/maxscheijen"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Hypothesis Testing</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Max Scheijen </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 9, 2022</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<p>In this post I want to give a basic introduction to confidence intervals.</p>
<p><strong>Statistics inference</strong> refers to the practice of makeing predictions about a larger group (generalization) based on a smaller group (samples). This prediction is usually coupled with a metric about the statistical uncertainty (confidence interval). This uncertainty allows us to express our confidence in our prediction. If we want higher confidence, we must report a wider interval.</p>
<p>So we usualy statistical inference has to parts <strong>estimation</strong> and <strong>hypothesis testing</strong>.</p>
<p>Throughout this post we use the following example:</p>
<blockquote class="blockquote">
<p>We survey <span class="math inline">\(1000\)</span> random people, and we observe <span class="math inline">\(140\)</span> are smokers. Therefore we estimate that the sample mean of smokers is <span class="math inline">\(140\)</span>, with a confidence interval of <span class="math inline">\(118\)</span> and <span class="math inline">\(162\)</span> at a <span class="math inline">\(95\%\)</span> confidence level.</p>
</blockquote>
<p>When looking a the example above, eventhough it may seem intuative, does not mean that we can say that with <span class="math inline">\(95\%\)</span> probability the true population mean of smokers is between <span class="math inline">\(118\)</span> and <span class="math inline">\(162\)</span>. However it does mean that if we take lots of samples, the population mean will be in this interval <span class="math inline">\(95\%\)</span> of the time.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside">Accepting a hypothesis as true based on a test, that doesn’t mean it’s <strong>definitely</strong> true. It means we know the probability we are wrong.</span></div></div>
<p>The above statement gives us an idea of the specific characteristics of smoking in the overall population based on our sample. <strong>Hypothesis testing</strong> is however different, it’s a framework for statistical testing of hypothesized values. We do this by making an assertion of what the amount of smokers should be. This creates a testable hypothesis that we can accept or put aside.</p>
<section id="hypothesis" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>The null hypothesis, commonly written as <span class="math inline">\(H_0\)</span>. The null hypothesis is the default case, generally reflecting the current common conception of the world. The alternative hypothesis is the one you are testing.</p>
<p>Not every hypthesis easily tested. Different hypothesis lead to higher or lower testing difficulty. For example, we have the following null hypothesis <em>‘unemploymend is not 140’</em> and an alternative hypothesis ‘unemployment is larger than 140’.</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="aside"><span class="math inline">\(H_{0}\)</span>: unemploymend <span class="math inline">\(\neq 140\)</span> <br> <span class="math inline">\(H_{1}\)</span>: unemploymend <span class="math inline">\(&gt; 140\)</span></span></div></div>
<p>This hypothesis pair are relativly easy to test. We can simply test the hypothesis by counting the number of unemployed people. However, you will still not get a perfect answer all the time in this case, as there may be measurement error in the counting, albiet quite small.</p>
<p>On the other hand, the hypothesis, the following hypothesis is harder to test.</p>
<blockquote class="blockquote">
<p><em>‘The percentage unemployemend is larger when the trains run on time’</em>.</p>
</blockquote>
<p>Eventhough it may sound silly, testing this hypothisis would be more difficult to test and requires us to gather a lot of data.</p>
<p>A hypothesis <strong>must be testable</strong> and cannot be vague. For example, “unemploymend larger than <span class="math inline">\(20\%\)</span> is not optimal”. What does ‘optimal’ mean? Hypotheses should be very specific and the type of test needed should follow quickly from the hypothesis.</p>
</section>
<section id="performing-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="performing-hypothesis-testing">Performing Hypothesis Testing</h2>
<p>We always following these six basic steps in hypothesis testing:</p>
<ol type="1">
<li>Construct hypothesis and the alternative to the hypothesis.</li>
<li>Identify the appropriate test statistic and its distribution. Ensure that any assumptions about the data are met (stationarity, normality, etc.)</li>
<li>Specify the significance level, <span class="math inline">\(\alpha\)</span></li>
<li>From <span class="math inline">\(\alpha\)</span> and the distribution compute the ‘critical value’.</li>
<li>Collect the data and calculate the test statistic</li>
<li>Compare test statistic with critical value and decide whether to accept or reject the hypothesis.</li>
</ol>
<p>First we state the hypothesis that we wish to test. We do this by identifying a <strong>null hypothesis</strong> and an <strong>alternative hypothesis</strong>. The null hypothesis, <span class="math inline">\(H_0\)</span>, is the one that we want to test, while the alternative hypothesis, <span class="math inline">\(H_A\)</span>, is the hypothesis that is accepted in the case where <span class="math inline">\(H_0\)</span> is rejected.</p>
<p>Let’s say that we want to test whether the mean return of Microsoft stock is positive. The parameter that we are testing is denoted by <span class="math inline">\(\theta\)</span> and the proposed value of the parameter is denoted by <span class="math inline">\(\theta_0\)</span>, which in this case is equal to <span class="math inline">\(0\)</span>. So we say that our <span class="math inline">\(H_0\)</span> is <span class="math inline">\(\theta = \theta_0\)</span>, that the returns are negative, and our <span class="math inline">\(H_A\)</span> is <span class="math inline">\(\theta \neq \theta_0\)</span>. Including this formation, there are three possible ways to formulate null and alternative hypotheses:</p>
<ol type="1">
<li><span class="math inline">\(H_0: \theta = \theta_0\)</span> versus <span class="math inline">\(H_A: \theta \neq \theta_0\)</span> (A “not equal to” alternative hypothesis)</li>
<li><span class="math inline">\(H_0: \theta \leq \theta_0\)</span> versus <span class="math inline">\(H_A: \theta &gt; \theta_0\)</span> (A “greater than” alternative hypothesis)</li>
<li><span class="math inline">\(H_0: \theta \geq \theta_0\)</span> versus <span class="math inline">\(H_A: \theta &lt; \theta_0\)</span> (A “less than” alternative hypothesis)</li>
</ol>
<p>In this case, where we are testing the returns of MSFT, <span class="math inline">\(\theta = \mu_{MSFT}\)</span>, representing the stock’s mean returns. Since we are testing whether the returns are positive or negative, we have that <span class="math inline">\(\theta_0 = 0\)</span>. Our example follows the first formulation of a hypothesis test. This is a <strong>two-sided hypothesis test</strong> (or <strong>two-tailed hypothesis test</strong>). The second and third formulations are examples of a <strong>one-sided hypothesis test</strong> (or <strong>one-tailed hypothesis test</strong>). With a one-sided test, we reject the null in favor of the alternative only if the data indivates that <span class="math inline">\(\theta\)</span> is repectively greater than or less than <span class="math inline">\(\theta_0\)</span>. A two-sided test rejects the null in favor of the alternative if the data indicates that <span class="math inline">\(\theta\)</span> is either greater or less than <span class="math inline">\(\theta_0\)</span>.</p>
<p>So if we were to write out our hypothesis for MSFT in more qualitative terms, we would have:</p>
<p><span class="math display">\[\begin{eqnarray}
H_0 &amp;:&amp; \text{The mean return on Microsoft stock is $0$}\\
H_A &amp;:&amp; \text{The mean return on Microsoft stock is not $0$}
\end{eqnarray}\]</span></p>
<p>When forming a hypothesis test, the null and alternative hypothesis must be complementary to each other. Between them they must cover all values of <span class="math inline">\(\theta\)</span>. Regardless of the type of hypothesis test we are performing, we always test the null hypothesis as if <span class="math inline">\(\theta = \theta_0\)</span>. In the case of either of the one-tailed tests, this will still provide more than enough evidence for us to make a decision. For example, if <span class="math inline">\(H_0: \theta \leq 0\)</span>, <span class="math inline">\(H_A: \theta &gt; 0\)</span>, and we have enough evidence to reject <span class="math inline">\(H_0: \theta = 0\)</span> in favor of <span class="math inline">\(H_A: \theta &gt; 0\)</span>, then this holds true for all values less than <span class="math inline">\(0\)</span> as well.</p>
<p>The most common type of hypothesis test is the two-tailed, “not equal to”, hypothesis test, because it presents a neutral view. The one-tailed hypothesis tests are less neutral than the “not equal to” test, reflecting the thoughts of the tester. One-tailed tests are often used to test “hoped for” results or results that the testers have a prior idea about.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:true}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s get some data.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="st">"2015-01-01"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="st">"2016-01-01"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>pricing_sample <span class="op">=</span> get_pricing(<span class="st">"MSFT"</span>, start_date <span class="op">=</span> start, end_date <span class="op">=</span> end, fields <span class="op">=</span> <span class="st">'price'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#transform it into returns</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>returns_sample <span class="op">=</span> pricing_sample.pct_change()[<span class="dv">1</span>:]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot it</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>plt.plot(pricing_sample.index, pricing_sample.values)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Price'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-3-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Here are the returns.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>plt.plot(returns_sample.index, returns_sample.values)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Returns'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-4-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="why-is-this-all-necessary" class="level2">
<h2 class="anchored" data-anchor-id="why-is-this-all-necessary">Why is this all necessary?</h2>
<p>Why can’t we just take the mean returns of microsoft and check if they’re &gt; 0? Because we can’t look at the actual data generating process behind the returns, we can only sample returns on some limited time period. Because we only observe a sample, that sample may or may not reflect the true state of the underlying process. Because of this uncertainty we need to use statistical tests.</p>
<p>Next, we identify the appropriate <strong>test statistic</strong> and its probability distribution. A test statistic usually takes the following form:</p>
<p><span class="math display">\[ \text{Test statistic} = \frac{\text{Sample statistic} - \text{Value of the population parameter under $H_0$ ($\theta_0$)}}{\text{Standard error of the sample statistic}} \]</span></p>
<p>A test statistic is calculated based on sample data and is compared to its probability distribution to determine whether to reject or not reject the null hypothesis. Since we are testing the mean return on MSFT stock, we can use the sample mean, <span class="math inline">\(\bar{X}_\mu\)</span>, as our sample statistic. We calculate the standard error of the sample mean as <span class="math inline">\(\sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}}\)</span> if we know the standard deviation, <span class="math inline">\(\sigma\)</span>, or as <span class="math inline">\(s_{\bar{X}} = \frac{s}{\sqrt{n}}\)</span>, where <span class="math inline">\(s\)</span> is the sample standard deviation. So using these definitions, our test statistic can be calculated as:</p>
<p><span class="math display">\[ \frac{\bar{X}_\mu - \theta_0}{s_{\bar{X}}} = \frac{\bar{X}_\mu - 0}{s/\sqrt{n}} \]</span></p>
<p>The four most common distributions for test statistics are as follows:</p>
<ul>
<li>The <span class="math inline">\(t\)</span>-distribution (<span class="math inline">\(t\)</span>-test)</li>
<li>The standard normal distribution (<span class="math inline">\(z\)</span>-test)</li>
<li>The chi-square (<span class="math inline">\(\chi^2\)</span>) distribution (<span class="math inline">\(\chi^2\)</span>-test)</li>
<li>The <span class="math inline">\(F\)</span>-distribution (<span class="math inline">\(F\)</span>-test)</li>
</ul>
<p>We will cover them in detail later. For now, we will say that we can use a <span class="math inline">\(z\)</span>-test with our assumptions in the MSFT example.</p>
<p>After we identify the appropriate test statistic and probability distribution, we need to specify the <strong>significance level</strong> of the test, <span class="math inline">\(\alpha\)</span>. The values that we compare our test statistic to in order to reject or fail to reject the <span class="math inline">\(H_0\)</span> are determined based on our <span class="math inline">\(\alpha\)</span> value.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">True Situation</th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Decision</strong></td>
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> True</td>
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> False</td>
</tr>
<tr class="even">
<td style="text-align: center;">Do not reject <span class="math inline">\(H_0\)</span></td>
<td style="text-align: center;">Correct Decision</td>
<td style="text-align: center;">Type II Error</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Reject <span class="math inline">\(H_0\)</span> (accept <span class="math inline">\(H_A\)</span>)</td>
<td style="text-align: center;">Type I Error</td>
<td style="text-align: center;">Correct Decision</td>
</tr>
</tbody>
</table>
<p>Our significance level is equal to the probability of a Type I error (a “false positive”) occuring. The probability of a Type II error (a “false negative”) occuring is denoted by <span class="math inline">\(\beta\)</span>. If we try to decrease the probability of a Type I error occuring, we increase the probability of a Type II error occuring, resulting in a tradeoff. The only way to reduce the probability of both a Type I and a Type II error occuring is to increase the sample size.</p>
<p>The conventional significance levels are <span class="math inline">\(0.1\)</span>, <span class="math inline">\(0.05\)</span>, and <span class="math inline">\(0.01\)</span>. Rejecting the null at <span class="math inline">\(0.1\)</span> mean that we have some evidence null is false, <span class="math inline">\(0.05\)</span> means we have strong evidence null is false, rejecting at <span class="math inline">\(0.01\)</span> we have very strong evidence that null is false.</p>
<section id="critical-value" class="level3">
<h3 class="anchored" data-anchor-id="critical-value">Critical Value</h3>
<p>Now we figure out our critical value, or, rejection point. The critical value for our test statistic is the value that we compare the test statistic to when deciding whether to reject the null hypothesis. If we reject the null, we say that the result is <strong>statistically significant</strong>, while if we fail to reject the null, we say that the result is <strong>not statistically significant</strong>.</p>
<p>We compare our test statistic to a <strong>critical value</strong> in order to decide whether to reject or not reject the null hypothesis. The critical value of a test is determined based on the <span class="math inline">\(\alpha\)</span> of our hypothesis test as well as the chosen distribution. In our case, say that <span class="math inline">\(\alpha = 0.05\)</span>, so our significance level is <span class="math inline">\(0.05\)</span>. With a one-sided <span class="math inline">\(z\)</span>-test, there are two different ways to see the critical values:</p>
<ul>
<li>If we test <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\theta \leq \theta_0\)</span>, <span class="math inline">\(H_A\)</span>: <span class="math inline">\(\theta &gt; \theta_0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>, our critical value is <span class="math inline">\(z_{0.05} = 1.645\)</span>. So we compare our test statistic and we reject the null hypothesis if <span class="math inline">\(z &gt; 1.645\)</span>.</li>
<li>If we test <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\theta \geq \theta_0\)</span>, <span class="math inline">\(H_A\)</span>: <span class="math inline">\(\theta &lt; \theta_0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>, our critical value is <span class="math inline">\(-z_{0.05} = -1.645\)</span>. As such, we compare our test statistic and we reject the null hypothesis if <span class="math inline">\(z &lt; -1.645\)</span>.</li>
</ul>
<p>A two-sided test is a slightly different situation. Since it is two-sided, there are two rejection points, negative and positive. Our <span class="math inline">\(\alpha\)</span> is <span class="math inline">\(0.05\)</span>, so the total probability of a Type I error must sum to <span class="math inline">\(0.05\)</span>. As such, we split <span class="math inline">\(0.05\)</span> in half so that our two rejection points are <span class="math inline">\(z_{0.025}\)</span> and <span class="math inline">\(-z_{0.025}\)</span> for the positive and negative critical values, respectively. For a <span class="math inline">\(z\)</span>-test, these values are <span class="math inline">\(1.96\)</span> and <span class="math inline">\(-1.96\)</span>. Thus, we reject the null if <span class="math inline">\(z &lt; -1.96\)</span> or if <span class="math inline">\(z &gt; 1.96\)</span>. If we find that <span class="math inline">\(-1.96 \leq z \leq 1.96\)</span>, we fail to reject the null.</p>
<p>When conducting a hypothesis test, you can also use a <strong><span class="math inline">\(p\)</span>-value</strong> to determine the result. A <span class="math inline">\(p\)</span>-value is the minimum level of significance where you can reject the null hypothesis. Often people will interpret <span class="math inline">\(p\)</span>-values as the “probability that the null hypothesis is false”, but this is misleading. A <span class="math inline">\(p\)</span>-value only makes sense when compared to the significance value. If a <span class="math inline">\(p\)</span>-value is less than <span class="math inline">\(\alpha\)</span>, we reject the null and otherwise we do not. Lower <span class="math inline">\(p\)</span>-values do not make something “more statistically significant”. A lot of statistical outputs will calculate a <span class="math inline">\(p\)</span>-value for you, but it is also possible to calculate it manually. The calculation depends both on your type of hypothesis test and the CDF (covered in the <a href="https://www.quantopian.com/lectures/random-variables">random variables lecture</a>) of the distribution you are working with. To manually calculate a <span class="math inline">\(p\)</span>-value, do the following:</p>
<ul>
<li>In a ‘less than or equal to’ hypothesis test, the <span class="math inline">\(p\)</span>-value is <span class="math inline">\(1 - CDF(\text{Test Statistic})\)</span></li>
<li>In a ‘greater than or equal to’ hypothesis test, the <span class="math inline">\(p\)</span>-value is <span class="math inline">\(CDF(\text{Test Statistic})\)</span></li>
<li>In a ‘not equal to’ hypothesis test, the <span class="math inline">\(p\)</span>-value is <span class="math inline">\(2 * 1 - CDF(|\text{Test Statistic}|)\)</span></li>
</ul>
<p>Significance values tie very nicely into confidence intervals, which are covered more in-depth in our <a href="https://www.quantopian.com/lectures/confidence-intervals">confidence intervals lecture</a>. A confidence interval provides us with an estimate for a parameter’s possible range in values given a certain significance level. For example, if our <span class="math inline">\(99\%\)</span> confidence interval for the mean of MSFT returns was <span class="math inline">\((-0.0020, 0.0023)\)</span>, that would mean that there was a <span class="math inline">\(99\%\)</span> chance that the true value of the mean was within that interval.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a standard normal distribution and mark the critical regions with shading</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">100</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>norm_pdf <span class="op">=</span> <span class="kw">lambda</span> x: (<span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span> <span class="op">*</span> np.pi)) <span class="op">*</span> np.exp(<span class="op">-</span>x <span class="op">*</span> x <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> norm_pdf(x)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>, sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>ax.fill_between(x, <span class="dv">0</span>, y, where <span class="op">=</span> x <span class="op">&gt;</span> <span class="fl">1.96</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>ax.fill_between(x, <span class="dv">0</span>, y, where <span class="op">=</span> x <span class="op">&lt;</span> <span class="op">-</span><span class="fl">1.96</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Rejection regions for a two-tailed hypothesis test at 95</span><span class="sc">% c</span><span class="st">onfidence'</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'p(x)'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-5-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Now we collect the relevant data for our test and calculate the test statistic for a two sided, <span class="math inline">\(5\%\)</span> significance test. Keep in mind that any negative characteristics of the data will negatively affect our hypothesis test and possibly render it invalid. In the case of our test of MSFT returns, we may run into issues of time-period bias, or of look-ahead bias (if we prepare the test incorrectly). As always with historical data, the data that we work with may result in a specific test result that may not hold for the future. We also have to make sure that the data does not include any values that we would not have known during the time period we are testing (though this is more of an issue when comparing multiple things with hypothesis tests).</p>
<p>Here we calculate the test statistic:</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(returns_sample)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>test_statistic <span class="op">=</span> ((returns_sample.mean() <span class="op">-</span> <span class="dv">0</span>) <span class="op">/</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                (returns_sample.std()<span class="op">/</span>np.sqrt(n)))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'t test statistic: '</span>, test_statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t test statistic:  0.740593955141</code></pre>
</div>
</div>
<p>In order to make the statistical decision for the test, we compare our test statistic to our critical value. Our test statistic as stated above is between the two critical values for a 95% two-tailed <span class="math inline">\(z\)</span>-test so in this example we <strong>fail to reject</strong> our <span class="math inline">\(H_0\)</span>, our hypothesis that MSFT returns are <strong>not</strong> <span class="math inline">\(0\)</span>.</p>
<p>If we chose instead to determine the result of this hypothesis test with a <span class="math inline">\(p\)</span>-value, we would calculate the <span class="math inline">\(p\)</span>-value in the following way:</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:true}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-scrolled="true" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> t.cdf(test_statistic, n <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'P-value is: '</span>, p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value is:  0.459634667217</code></pre>
</div>
</div>
<p>Because the <span class="math inline">\(p\)</span>-value is greater than our significance level, <span class="math inline">\(\alpha = 0.05\)</span>, we <strong>fail to reject</strong> the null hypothesis.</p>
<p>After we make the statistical decision, we have to translate it into real life. Oftentimes this may be difficult to act upon directly, but the results can have other implications. In the case of our example, we have found that the daily returns of Microsoft in 2015 were not significantly different from <span class="math inline">\(0\)</span>.</p>
</section>
</section>
<section id="hypothesis-testing-on-means" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-on-means">Hypothesis Testing on Means</h2>
<p>A <span class="math inline">\(z\)</span>-distribution, or a standard normal distribution, is an essential probability distribution in finance. We like it when things are normally distributed because it entails many useful properties. On top of this, many fundamental methods require an assumption of normality in order to proceed. However, in most cases a <span class="math inline">\(z\)</span>-distribution will be inappropriate for our data. We rarely know the true parameter values (mean and variance) of our data and must rely upon approximations. In these cases, we should use the <span class="math inline">\(t\)</span>-distribution, and approximation of the normal distribution. The <span class="math inline">\(t\)</span>-distribution is more forgiving when it comes to small sample sizes and is meant to be used with sample mean and variance. It has fatter tails and a lower peak, giving more flexibility compared to a normal distribution.</p>
<p>Both the <span class="math inline">\(t\)</span> and <span class="math inline">\(z\)</span>-distributions rely upon an underlying assumption of normality, which is typically the case when we are analyzing financial data. As such, in addition to testing individual means, it makes sense to use them to compare between two or more mean values. We can use a hypothesis test to determine whether the means of several data-sets are statistically different from one another. Here, we will use a <span class="math inline">\(t\)</span>-distribution to demonstrate. We will compare the mean returns of the S&amp;P500 and Apple stock with a hypothesis test to see if the differences are statistically significant or not.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>symbol_list <span class="op">=</span> [<span class="st">"SPY"</span>, <span class="st">"AAPL"</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="st">'2015-01-01'</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="st">'2016-01-01'</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>pricing_sample <span class="op">=</span> get_pricing(symbol_list, start_date <span class="op">=</span> start, end_date <span class="op">=</span> end, fields<span class="op">=</span><span class="st">'price'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>pricing_sample.columns <span class="op">=</span> <span class="bu">map</span>(<span class="kw">lambda</span> x: x.symbol, pricing_sample.columns)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>returns_sample <span class="op">=</span> pricing_sample.pct_change()[<span class="dv">1</span>:]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>returns_sample.plot()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Returns'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>While these returns look to have the same mean, we still don’t have enough evidence to say for sure. We use a hypothesis test to ground our suspicions in a statistical basis.</p>
<p>When comparing two means, our hypothesis tests are stated as the following:</p>
<ol type="1">
<li><span class="math inline">\(H_0: \mu_1 - \mu_2 = \theta_0, \ H_A: \mu_1 - \mu_2 \neq \theta_0\)</span></li>
<li><span class="math inline">\(H_0: \mu_1 - \mu_2 \leq \theta_0, \ H_A: \mu_1 - \mu_2 &gt; \theta_0\)</span></li>
<li><span class="math inline">\(H_0: \mu_1 - \mu_2 \geq \theta_0, \ H_A: \mu_1 - \mu_2 &lt; \theta_0\)</span></li>
</ol>
<p>Where <span class="math inline">\(\mu_1, \mu_2\)</span> are the respective means of SPY and AAPL and <span class="math inline">\(\theta_0\)</span> is the parameter we are testing. We will use the first hypothesis test to test the equality of the two returns. If we assume that the population variances are equal, our test statistic is calculated as:</p>
<p><span class="math display">\[ t = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{(\frac{s_p^2}{n_1} + \frac{s_p^2}{n_2})^{1/2}} = \frac{\bar{X}_1 - \bar{X}_2}{(\frac{s_p^2}{n_1} + \frac{s_p^2}{n_2})^{1/2}}\]</span></p>
<p>With <span class="math inline">\(s_p^2 = \frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2)}{n_1 + n_2 - 2}\)</span> as the estimator of the common variance, known as the pooled variance, and <span class="math inline">\(n_1 + n_2 - 2\)</span> as the number of degrees of freedom (<span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> for each dataset). A typical <span class="math inline">\(t\)</span>-test on a mean assumes that all variances involved are equal with underlying normal distributions. If we are assuming that the variances are not equal, we have to calculate our test statistic differently. Our test statistic in this case is:</p>
<p><span class="math display">\[ t = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{(\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2})^{1/2}} = \frac{\bar{X}_1 - \bar{X}_2}{(\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2})^{1/2}}\]</span></p>
<p>Where the number of degrees of freedom used to find the critical statistic is the modified degrees of freedom, the number of values that are free to vary, <span class="math inline">\(df = \frac{(\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2})^2}{\frac{(s_1^2/n_1)^2}{n_1} + \frac{(s_2^2/n_2)^2}{n_2}}\)</span>. This preserves the underlying normality of the data being tested while accounting for differing variances. Calculating the statistic this way removes a lot of problems that can occur if we have unequal variances, especially if the sample sizes of the underlying data differ as well. This specific case of a <span class="math inline">\(t\)</span>-test is referred to as <a href="https://en.wikipedia.org/wiki/Welch%27s_t-test">“Welch’s unequal variances <span class="math inline">\(t\)</span>-test”</a>.</p>
<p>For this example, we are assuming that the variances of SPY and AAPL returns are different. We think that AAPL will be riskier than SPY so we will use the second formulation of the test statistic. Let’s say that <span class="math inline">\(\alpha = 0.05\)</span> so we are computing a <span class="math inline">\(95\%\)</span> hypothesis test.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample mean values</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mu_spy, mu_aapl <span class="op">=</span> returns_sample.mean()</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>s_spy, s_aapl <span class="op">=</span> returns_sample.std()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>n_spy <span class="op">=</span> <span class="bu">len</span>(returns_sample[<span class="st">'SPY'</span>])</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>n_aapl <span class="op">=</span> <span class="bu">len</span>(returns_sample[<span class="st">'AAPL'</span>])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>test_statistic <span class="op">=</span> ((mu_spy <span class="op">-</span> mu_aapl) <span class="op">-</span> <span class="dv">0</span>)<span class="op">/</span>((s_spy<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_spy) <span class="op">+</span> (s_aapl<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_aapl))<span class="op">**</span><span class="fl">0.5</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> ((s_spy<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_spy) <span class="op">+</span> (s_aapl<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_aapl))<span class="op">**</span><span class="dv">2</span><span class="op">/</span>(((s_spy<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> n_spy)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span>n_spy)<span class="op">+</span>((s_aapl<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> n_aapl)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_aapl))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'t test statistic: '</span>, test_statistic</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Degrees of freedom (modified): '</span>, df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t test statistic:  0.023740009212
Degrees of freedom (modified):  405.251211662</code></pre>
</div>
</div>
<p>Looking at a <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution#Table_of_selected_values">t-table</a>, we determine that the critical values for our two-sided hypothesis test are <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span>. Our test statistic is between these values so we <strong>fail to reject</strong> the null hypothesis and determine that the difference between SPY and AAPL returns is <strong>not</strong> significantly different from <span class="math inline">\(0\)</span>.</p>
</section>
<section id="hypothesis-testing-on-variances" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-on-variances">Hypothesis Testing on Variances</h2>
<p>If we want to test the variances of populations, we need to use a different distribution from the <span class="math inline">\(t\)</span> and <span class="math inline">\(z\)</span> distributions. Variances must by definition be greater than (or equal to) <span class="math inline">\(0\)</span> and fact that the distributions we have worked with up until now allow negative values makes them unviable as testing distributions. Risk is quantified in terms of standard deviations and variances so this method of hypothesis testing is a handy addition to our financial toolbox.</p>
<p>Instead of <span class="math inline">\(t\)</span> and <span class="math inline">\(z\)</span>-distributions, we will be working with <span class="math inline">\(\chi^2\)</span> distributions for single variance tests and <span class="math inline">\(F\)</span> distributions for comparisons of variance. These distributions are bounded below by <span class="math inline">\(0\)</span>, making them viable for testing in this manner.</p>
<p>Just like with all of our other hypothesis tests, tests of a single variance can take on three forms:</p>
<ol type="1">
<li><span class="math inline">\(H_0: \sigma^2 = \sigma_0^2, \ H_A: \sigma^2 \neq \sigma_0^2\)</span></li>
<li><span class="math inline">\(H_0: \sigma^2 \leq \sigma_0^2, \ H_A: \sigma^2 &gt; \sigma_0^2\)</span></li>
<li><span class="math inline">\(H_0: \sigma^2 \geq \sigma_0^2, \ H_A: \sigma^2 &lt; \sigma_0^2\)</span></li>
</ol>
<p>The <span class="math inline">\(\chi^2\)</span> distribution is a family of functions with each different formulation determined by the number of degrees of freedom. The shape of the distribution is different for every different value of the number of degrees of freedom, <span class="math inline">\(k\)</span>.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we show what a chi-square looks like</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">8</span>, <span class="dv">100</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>y_1 <span class="op">=</span> chi2.pdf(x, <span class="dv">1</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>y_2 <span class="op">=</span> chi2.pdf(x, <span class="dv">2</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>y_3 <span class="op">=</span> chi2.pdf(x, <span class="dv">3</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>y_4 <span class="op">=</span> chi2.pdf(x, <span class="dv">4</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>y_6 <span class="op">=</span> chi2.pdf(x, <span class="dv">6</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>y_9 <span class="op">=</span> chi2.pdf(x, <span class="dv">9</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_1, label <span class="op">=</span> <span class="st">'k = 1'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_2, label <span class="op">=</span> <span class="st">'k = 2'</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_3, label <span class="op">=</span> <span class="st">'k = 3'</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_4, label <span class="op">=</span> <span class="st">'k = 4'</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_6, label <span class="op">=</span> <span class="st">'k = 6'</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y_9, label <span class="op">=</span> <span class="st">'k = 9'</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Chi-Square distribution with k degrees of freedom'</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'p(x)'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We calculate the <span class="math inline">\(\chi^2\)</span> test statistic as:</p>
<p><span class="math display">\[ \chi^2 = \frac{(n - 1)s^2}{\sigma_0^2} \]</span></p>
<p>Where <span class="math inline">\(s^2\)</span> is the sample variance and <span class="math inline">\(n\)</span> is the size of the dataset. The number of degrees of freedom is <span class="math inline">\(n - 1\)</span> and this is used in conjunction with the test statistic to determine the critical value(s) of our <span class="math inline">\(\chi^2\)</span> hypothesis test.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="st">"2015-01-01"</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="st">"2016-01-01"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>pricing_sample <span class="op">=</span> get_pricing(<span class="st">"MSFT"</span>, start_date <span class="op">=</span> start, end_date <span class="op">=</span> end, fields <span class="op">=</span> <span class="st">'price'</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>returns_sample <span class="op">=</span> pricing_sample.pct_change()[<span class="dv">1</span>:]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>plt.plot(returns_sample.index, returns_sample.values)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Returns'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hypothesis-testing_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Now we will use a <span class="math inline">\(\chi^2\)</span>-test to test the value of the variance of Microsoft stock. Let’s say that we want to use <span class="math inline">\(\alpha = 0.01\)</span> to test whether the variance of MSFT is less than or equal to <span class="math inline">\(0.0001\)</span> (that the standard deviation, or risk, is less than or equal to <span class="math inline">\(0.01\)</span>).</p>
<p><span class="math display">\[ H_0: \sigma^2 \leq 0.0001, \ H_A: \sigma^2 &gt; 0.0001 \]</span></p>
<p>So now we calculate our test statistic:</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>test_statistic <span class="op">=</span> (<span class="bu">len</span>(returns_sample) <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> returns_sample.std()<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> <span class="fl">0.0001</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Chi-square test statistic: '</span>, test_statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-square test statistic:  805.372389966</code></pre>
</div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we calculate the critical value directly because our df is too high for most chisquare tables</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>crit_value <span class="op">=</span> chi2.ppf(<span class="fl">0.99</span>, <span class="bu">len</span>(returns_sample) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Critical value at a = 0.01 with 251 df: '</span>, crit_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical value at a = 0.01 with 251 df:  304.939555734</code></pre>
</div>
</div>
<p>Because we are using the ‘less than or equal to’ formulation of a one-sided hypothesis test, we reject the null hypothesis if our test statistic is greater than the critical value. Since <span class="math inline">\(805.372 &gt; 304.940\)</span>, we <strong>reject</strong> the null hypothesis in favor of the alternative and assert that <span class="math inline">\(\sigma^2 &gt; 0.0001\)</span>.</p>
<section id="comparing-two-variances" class="level3">
<h3 class="anchored" data-anchor-id="comparing-two-variances">Comparing Two Variances</h3>
<p>We can compare the variances of two separate things using the <span class="math inline">\(F\)</span> distribution. When constructing a comparison of variances using an <span class="math inline">\(F\)</span>-test, the hypothesis formulations are (in case you don’t feel like scrolling up):</p>
<ol type="1">
<li><span class="math inline">\(H_0: \sigma_1^2 = \sigma_2^2, \ H_A: \sigma_1^2 \neq \sigma_2^2\)</span></li>
<li><span class="math inline">\(H_0: \sigma_1^2 \leq \sigma_2^2, \ H_A: \sigma_1^2 &gt; \sigma_2^2\)</span></li>
<li><span class="math inline">\(H_0: \sigma_1^2 \geq \sigma_2^2, \ H_A: \sigma_1^2 &lt; \sigma_2^2\)</span></li>
</ol>
<p>The <span class="math inline">\(F\)</span> distribution is similar to the <span class="math inline">\(\chi^2\)</span> distribution in that it is asymmetrical and bounded below by <span class="math inline">\(0\)</span>. The <span class="math inline">\(F\)</span> distribution is defined with two different values of degrees of freedom. For the purposes of hypothesis testing, each one correlates to one of the factors that we are comparing. An <span class="math inline">\(F\)</span> distribution can be constructed from two separate <span class="math inline">\(\chi^2\)</span> distributions. <span class="math inline">\(X\)</span> is a <span class="math inline">\(F\)</span> random variable if it can be written as <span class="math inline">\(X = \frac{Y_1/d_1}{Y_2/d_2}\)</span>, where <span class="math inline">\(Y_1\)</span> and <span class="math inline">\(Y_2\)</span> are <span class="math inline">\(\chi^2\)</span> random variables with degrees of freedom <span class="math inline">\(d_1\)</span> and <span class="math inline">\(d_2\)</span>, respectively.</p>
<p>The an <span class="math inline">\(F\)</span> random variable is essentially a ratio of variances. Consequently, constructing the <span class="math inline">\(F\)</span> test statistic is done by taking the ratio of the sample variances of the data that we want to test. We can simply choose <span class="math inline">\(\sigma_1^2\)</span> and <span class="math inline">\(\sigma_2^2\)</span> to represent either of the variances that we are comparing in order so that our F-statistic is greater than <span class="math inline">\(1\)</span>.</p>
<p><span class="math display">\[ F = \frac{s_1^2}{s_2^2} \]</span></p>
<p>Let’s compare SPY and AAPL to see whether their variances are the same (a ‘not equal to’ hypothesis test). We will use a <span class="math inline">\(\alpha = 0.05\)</span> test. Recall that for a two-sided test, we calculate the lower and upper critical values using values of <span class="math inline">\(\alpha/2\)</span>. We gather the data and calculate the test statistic.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>symbol_list <span class="op">=</span> [<span class="st">"SPY"</span>, <span class="st">"AAPL"</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="st">"2015-01-01"</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="st">"2016-01-01"</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>pricing_sample <span class="op">=</span> get_pricing(symbol_list, start_date <span class="op">=</span> start, end_date <span class="op">=</span> end, fields <span class="op">=</span> <span class="st">'price'</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>pricing_sample.columns <span class="op">=</span> <span class="bu">map</span>(<span class="kw">lambda</span> x: x.symbol, pricing_sample.columns)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>returns_sample <span class="op">=</span> pricing_sample.pct_change()[<span class="dv">1</span>:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take returns from above, AAPL and SPY, and compare their variances</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>spy_std_dev, aapl_std_dev <span class="op">=</span> returns_sample.std()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'SPY standard deviation is: '</span>, spy_std_dev</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'AAPL standard deviation is: '</span>, aapl_std_dev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SPY standard deviation is:  0.00989055656074
AAPL standard deviation is:  0.0168746184335</code></pre>
</div>
</div>
<p>Note that the standard deviation of AAPL is greater than the standard deviation of SPY. As a result we choose <span class="math inline">\(\sigma_1^2\)</span> to represent the variance of AAPL and <span class="math inline">\(\sigma_2^2\)</span> to represent the variance of SPY.</p>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>test_statistic <span class="op">=</span> (aapl_std_dev <span class="op">/</span> spy_std_dev)<span class="op">**</span><span class="dv">2</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">"F Test statistic: "</span>, test_statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F Test statistic:  2.91089447015</code></pre>
</div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Since these values are taken over the same time period, they will have the same number of degrees of freedom</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> <span class="bu">len</span>(returns_sample[<span class="st">'AAPL'</span>]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> <span class="bu">len</span>(returns_sample[<span class="st">'SPY'</span>]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Degrees of freedom for SPY: '</span>, df2</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Degrees of freedom for AAPL: '</span>, df1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Degrees of freedom for SPY:  250
Degrees of freedom for AAPL:  250</code></pre>
</div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:true}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-jupyter="{&quot;outputs_hidden&quot;:false}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>upper_crit_value <span class="op">=</span> f.ppf(<span class="fl">0.975</span>, df1, df2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>lower_crit_value <span class="op">=</span> f.ppf(<span class="fl">0.025</span>, df1, df2)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Upper critical value at a = 0.05 with df1 = </span><span class="sc">{0}</span><span class="st"> and df2 = </span><span class="sc">{1}</span><span class="st">: '</span>.<span class="bu">format</span>(df1, df2), upper_crit_value</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> <span class="st">'Lower critical value at a = 0.05 with df1 = </span><span class="sc">{0}</span><span class="st"> and df2 = </span><span class="sc">{1}</span><span class="st">: '</span>.<span class="bu">format</span>(df1, df2), lower_crit_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Upper critical value at a = 0.05 with df1 = 250 and df2 = 250:  1.28208064948
Lower critical value at a = 0.05 with df1 = 250 and df2 = 250:  0.779982133263</code></pre>
</div>
</div>
<p>We see that our F-statistic value is greater than the upper critical value for our F test. Thus we <strong>reject</strong> the null hypothesis in favor of the alternative and conclude that the variances of AAPL and SPY indeed do differ.</p>
</section>
</section>
<section id="other-resources" class="level2">
<h2 class="anchored" data-anchor-id="other-resources">Other Resources</h2>
<p>Some of the content featured here is adapted from “Quantitative Investment Analysis”, by DeFusco, McLeavey, Pinto, and Runkle.</p>
<p>More common test statistics and tests can be found <a href="https://en.wikipedia.org/wiki/Statistical_hypothesis_testing#Common_test_statistics">here</a>.</p>
<p><em>This presentation is for informational purposes only and does not constitute an offer to sell, a solicitation to buy, or a recommendation for any security; nor does it constitute an offer to provide investment advisory or other services by Quantopian, Inc.&nbsp;(“Quantopian”). Nothing contained herein constitutes investment advice or offers any opinion with respect to the suitability of any security, and any views expressed herein should not be taken as advice to buy, sell, or hold any security or as an endorsement of any security or company. In preparing the information contained herein, Quantopian, Inc.&nbsp;has not taken into account the investment needs, objectives, and financial circumstances of any particular investor. Any views expressed and data illustrated herein were prepared based upon information, believed to be reliable, available to Quantopian, Inc.&nbsp;at the time of publication. Quantopian makes no guarantees as to their accuracy or completeness. All information is subject to change and may quickly become unreliable for various reasons, including changes in market conditions or economic circumstances.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="maxscheijen/comments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>